### ISSUE TITLE
Add a Favicon

### ISSUE THREAD

**Issue by kishanpatel98** [MathBunny/model-car-inventory#32]
Add M-Sport Flag as webpage Favicon

**Comment by MathBunny** [comment]
Sounds like a good idea as there's no favicon currently. The only uncertainty I have around that is any potential licensing issues with the BMW brandname, but I suppose it should be fine.

Want to take a stab at it @kishanpatel98 ?

**Comment by MathBunny** [comment]
Closed as part of #33
